### ISSUE TITLE
Dead Code at FixedWidthFieldLengths

### ISSUE THREAD

**Issue by SolidSnackDrive** [SolidSnackDrive/univocity-parsers#3]
According to IntelliJ, this class is not actually used at all by the rest of the codebase.
Verify that removal will not affect anything, and then delete it.

**Comment by sispuella** [comment]
Issue closed because there are more dead code that can be safely deleted. Please refer to the new issue named "Dead Code Safe Deletion".

**Comment by sispuella** [comment]
Refactor was successful as all tests passed
