### ISSUE TITLE
Long Method and High Cyclomatic Complexity at FixedWidthParser

### ISSUE THREAD

**Issue by SolidSnackDrive** [SolidSnackDrive/univocity-parsers#4]
The class FixedWidthParser has a method "parseRecord" that goes on for 112 lines and has a complexity of 26. 
It is likely that solving one of these problems will likely solve the other as well.

**Comment by MustafaWasif** [comment]
Refactored successfully. 
Reduced lines of code from 108 to 27 lines.
Code Complexity reduced from 31 to 10.
